### ISSUE TITLE
Argon2 error attempting to generate constellation keys with password

### ISSUE THREAD

**Issue by Lsquared13** [jpmorganchase/constellation#62] opened 2017-12-07 00:27 UTC
Hi,

I am trying to generate a constellation key pair on an EC2 instance running ubuntu 16.04, and if I specify a password I get an error from Argon2.  I installed constellation with the binary provided for release v0.2.0, but I also encountered this problem with release v0.1.0.  If I leave the password blank my key pair is generated just fine, but if I specify a password I get the following error:

```
ubuntu@ip-<my-private-ip>:~$ constellation-node --generatekeys=node
Lock key pair node with password [none]: ****
constellation-node: argon2: hash: internal error
CallStack (from HasCallStack):
  error, called at ./Crypto/KDF/Argon2.hs:124:27 in cryptonite-0.22-4Pi0d9NUdk4EM6H9Pr9xLG:Crypto.KDF.Argon2
```

Any advice on what might be wrong or how I might get this to work would be appreciated.

**Comment by patrickmn** [comment] 2018-02-06 21:49
Perhaps you're running out of memory? The default parameters are currently set to require 1 GB of memory for the Argon2 stretching process.

**Comment by cartazio** [comment] 2018-04-17 22:42
Since theres not enough info to know if this is OOM on linux (enabling a SWAP file of sufficient size might be helpful?) or another issue, nor easy reproducer, i'm closing this for now.

please enable swap file per the other suggestion, if you can otherwise pin down a different cause, please share

**Closed by cartazio** 2018-04-17 22:42 UTC
